
title: Aprende
description: Guía de cosas en las que avanzo en mi día a día
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://erincon01.github.io/doc

aux_links:
  erincon01@github: https://github.com/erincon01/doc

#color_scheme: light (default)
#color_scheme: dark

search_enabled: true
search.button: true

search.previews: 3 -- default



collections:
  Azure:
    permalink: "/:collection/:path/"
    output: true
  SQLServer:
    permalink: "/:collection/:path/"
    output: true
  SobreDoc:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    Azure:
      name: Azure
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    SQLServer:
      name: SQL Server
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    SobreDoc:
      name: About
      nav_exclude: false
      nav_fold: true
      search_exclude: false


