
title: Aprende
description: Guía de cosas en las que avanzo en mi día a día
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://erincon01.github.io/doc

aux_links:
  erincon01@github: https://github.com/erincon01/doc

#color_scheme: light (default)
#color_scheme: dark

search_enabled: true
search.button: true

search.previews: 3 -- default

collections:
  DBA:
    permalink: "/:collection/:path/"
    output: true
  DevOps:
    permalink: "/:collection/:path/"
    output: true
  SecOps:
    permalink: "/:collection/:path/"
    output: true
  About:
    permalink: "/:collection/:path/"
    output: true
  JustTheDocs:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  collections:
    DBA:
      name: DBA
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    DevOps:
      name: DevOps
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    SecOps:
      name: SecOps
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    About:
      name: About
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    JustTheDocs:
      name: Just The Docs
      nav_exclude: false
      nav_fold: true
      search_exclude: true


